# Generated by Django 5.1.7 on 2025-11-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('contract', 'Контракт'), ('internship', 'Стажировка'), ('temporary', 'Временная работа')], default='full_time', max_length=20, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('no_exp', 'Без опыта'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='no_exp', max_length=20, verbose_name='Требуемый опыт'),
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='Знание языков (через запятую)'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='yt', max_length=200, verbose_name='Локация (город)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='Обязанности'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата от'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата до'),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.CharField(choices=[('office', 'Офис'), ('remote', 'Удалённо'), ('hybrid', 'Гибрид')], default='office', max_length=20, verbose_name='Формат работы'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Описание вакансии'),
        ),
    ]
